component: user
params: "DOCUMENTDB:dev.user.mongo,REDIS_HOST:dev.elasticache.endpoint,MONGO_URL:dev.docdb.user.url"
# params: "DOCUMENTDB:dev.user.mongo,REDIS_HOST:dev.user.redis_host,MONGO_URL:dev.user.mongo_url"

env: dev
schema:
  create: true
  type: mongo

resources:
   limits:
     cpu: 300m
     memory: 175Mi
   requests:
     cpu: 200m
     memory: 128Mi